#!/usr/bin/env bun
import { readdirSync, realpathSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const root = dirname(import.meta.dir);
const output = join(root, "THIRD_PARTY_NOTICES.txt");
const require = createRequire(import.meta.url);
const LICENSE_FILE = /^(?:license|licence|copying|notice)(?:$|[-_. ]+[a-z0-9]+(?:[-_. ]+[a-z0-9]+)*)$/i;

type Manifest = {
	name: string;
	version: string;
	license?: string | { type?: string };
	repository?: string | { url?: string };
	homepage?: string;
	dependencies?: Record<string, string>;
	optionalDependencies?: Record<string, string>;
};

function packageManifest(name: string, parentDirectory: string): { manifest: Manifest; directory: string } {
	const resolver = createRequire(join(parentDirectory, "__notice-resolver__.cjs"));
	const manifestPath = resolver.resolve(`${name}/package.json`);
	const directory = realpathSync(dirname(manifestPath));
	return { manifest: JSON.parse(require("node:fs").readFileSync(manifestPath, "utf8")) as Manifest, directory };
}

async function collect(): Promise<Array<{ manifest: Manifest; directory: string }>> {
	const seen = new Set<string>();
	const packages: Array<{ manifest: Manifest; directory: string }> = [];
	const visit = (name: string, parentDirectory: string) => {
		const resolved = packageManifest(name, parentDirectory);
		const identity = `${resolved.directory}\0${resolved.manifest.name}\0${resolved.manifest.version}`;
		if (seen.has(identity)) return;
		seen.add(identity);
		packages.push(resolved);
		for (const dependency of Object.keys({ ...resolved.manifest.dependencies, ...resolved.manifest.optionalDependencies }).sort()) visit(dependency, resolved.directory);
	};
	visit("puppeteer-core", root);
	return packages.sort((a, b) => a.manifest.name.localeCompare(b.manifest.name) || a.manifest.version.localeCompare(b.manifest.version) || a.directory.localeCompare(b.directory));
}

async function render(): Promise<string> {
	const packages = await collect();
	const sections: string[] = [
		"THIRD-PARTY NOTICES",
		"=======================",
		"",
		`Generated by \u0060bun run scripts/generate-third-party-notices.ts\u0060 from the production dependency closure of puppeteer-core@${packages.find(({ manifest }) => manifest.name === "puppeteer-core")?.manifest.version ?? "unknown"}.`,
		"",
	];
	for (const { manifest, directory } of packages) {
		const license = typeof manifest.license === "string" ? manifest.license : manifest.license?.type ?? "UNKNOWN";
		const repository = typeof manifest.repository === "string" ? manifest.repository : manifest.repository?.url ?? manifest.homepage ?? "";
		sections.push(`${manifest.name}@${manifest.version}`, `License: ${license}`, ...(repository ? [`Source: ${repository}`] : []));
		const licenseFile = readdirSync(directory).sort().find((name) => LICENSE_FILE.test(name));
		if (licenseFile) sections.push(`File: ${licenseFile}`, "", await readFile(join(directory, licenseFile), "utf8"));
	}
	return `${sections.join("\n").trimEnd()}\n`;
}

const rendered = await render();
if (process.argv.includes("--check")) {
	const current = await readFile(output, "utf8");
	if (current !== rendered) throw new Error(`${output} is stale; run the generator`);
	console.log(`PASS: ${output}`);
} else {
	await writeFile(output, rendered);
	console.log(`wrote ${output}`);
}
