name: CLA
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
permissions: {}
jobs:
  cla:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: CLA assistant
        uses: cla-assistant/github-action@v2.5.3
        if: ${{ vars.CLA_APP_ID != '' }}
        with:
          path-to-signatures: signatures/version.json
          branch: main
          allowlist: bot*
