import { describe, expect, test } from "bun:test";
import * as fs from "node:fs";
import * as path from "node:path";

const RULE=path.join(import.meta.dir,"ops-no-global-cargo-target.md");
function field(name:string):string{const t=fs.readFileSync(RULE,"utf8");const fm=/^---\r?\n([\s\S]*?)\r?\n---/.exec(t);if(!fm)throw new Error("no frontmatter");const l=(fm[1] as string).split(/\r?\n/).find(x=>x.startsWith(`${name}:`));if(!l)throw new Error(`no ${name}`);return l.slice(name.length+1).trim();}
function conditions():RegExp[]{return (JSON.parse(field("condition")) as string[]).map(p=>{const f=/^\(\?([ims]+)\)/.exec(p);return f?new RegExp(p.slice(f[0].length),f[1]):new RegExp(p);});}
/** Path globs of the scope's tool tokens; commas inside `{…}` and `(…)` stay with their token, as OMP reads them. */
function scopeGlobs():string[]{const s=JSON.parse(field("scope")) as string;const out:string[]=[];let depth=0,cur="";for(const c of s){if(c==="("||c==="{")depth++;if(c===")"||c==="}")depth--;if(c===","&&depth===0){out.push(cur.trim());cur="";}else cur+=c;}out.push(cur.trim());return out.map(t=>/\((.+)\)$/.exec(t)?.[1]).filter((g):g is string=>g!==undefined);}
/** Mirrors TTSR path matching: the glob against the full path, then against its basename. */
const inScope=(file:string)=>scopeGlobs().some(g=>{const glob=new Bun.Glob(g);return glob.match(file)||glob.match(path.basename(file));});
const FIRE=["target-dir = \"/tmp/shared\"","[build]\ntarget-dir = \"~/cargo-target\"","export CARGO_TARGET_DIR=/tmp/shared","export CARGO_TARGET_DIR=\"$HOME/.cache/target\"","CARGO_TARGET_DIR: /tmp/shared","env:\n  CARGO_TARGET_DIR: /tmp/shared","[env]\nCARGO_TARGET_DIR = \"{{env.HOME}}/.cache/cargo-target\"","CARGO_TARGET_DIR = {{ joinPath .chezmoi.cacheDir \"target\" | toJson }}","set -gx CARGO_TARGET_DIR ~/.cache/cargo-target","set -gx CARGO_TARGET_DIR \"$DEVELOPMENT_CACHE_HOME/target\""];
const HOLD=["echo target-dir = /tmp/shared","cargo build","[build]\ntarget-dir = \"target-ci\"","target-dir = \"../target\"","CARGO_TARGET_DIR: ${{ github.workspace }}/target","export CARGO_TARGET_DIR=target","set -gx CARGO_TARGET_DIR target"];
const WATCHED=["/repo/.cargo/config.toml","/repo/.github/workflows/ci.yml","/Users/u/.zshrc","/repo/mise.toml","/repo/.mise.toml","/Users/u/.config/mise/config.toml","/Users/u/.local/share/chezmoi/dot_config/mise/conf.d/05-development-cache.toml.tmpl","/Users/u/.local/share/chezmoi/dot_zshrc","/Users/u/.local/share/chezmoi/private_dot_zshenv.tmpl","/Users/u/.config/fish/config.fish","/Users/u/.local/share/chezmoi/dot_config/private_fish/conf.d/01_cache.fish.tmpl"];
describe("ops-no-global-cargo-target",()=>{const rs=conditions();for(const x of FIRE)test(`fires: ${x}`,()=>expect(rs.some(r=>r.test(x))).toBe(true));for(const x of HOLD)test(`holds: ${x}`,()=>expect(rs.some(r=>r.test(x))).toBe(false));for(const x of WATCHED)test(`watches: ${x}`,()=>expect(inScope(x)).toBe(true));test("ignores unrelated files",()=>expect(inScope("/repo/src/main.rs")).toBe(false));});
