#!/usr/bin/env python3
"""Fold installed .gitignore.d fragments into the managed .gitignore section.

    fold_gitignore.py <dest>

Every rule set is vendored in a fragment, one per subject, so this fetches nothing and
takes no template argument: the same tree folds to the same block offline.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

ALWAYS = """# Generated by a tool in this repository, never committed.
# Local state
*.log
"""
MANAGED_BEGIN = "# BEGIN PROJECT-SETUP MANAGED BLOCK"
MANAGED_END = "# END PROJECT-SETUP MANAGED BLOCK"


def fragments(dest: Path) -> str:
    directory = dest / ".gitignore.d"
    if not directory.is_dir():
        return ""
    blocks = []
    for fragment in sorted(directory.iterdir()):
        if not fragment.is_file() or fragment.name.startswith("."):
            continue
        body = fragment.read_text().strip()
        if not body:
            continue
        header = "" if body.startswith("#") else f"# {fragment.name}\n"
        blocks.append(f"{header}{body}\n")
    return "\n".join(blocks)


def managed_block(dest: Path) -> str:
    parts = [ALWAYS]
    fragment_text = fragments(dest)
    if fragment_text:
        parts.append(fragment_text)
    body = "\n".join(part.rstrip() + "\n" for part in parts if part)
    return f"{MANAGED_BEGIN}\n{body}{MANAGED_END}\n"


def write_managed(target: Path, block: str) -> None:
    if (target.exists() and not os.access(target, os.W_OK)) or (
        not target.exists() and not os.access(target.parent, os.W_OK)
    ):
        raise SystemExit(f"conflict: cannot write {target.name} without overwriting brownfield content")
    if not target.exists():
        target.write_bytes(block.encode())
        return

    existing = target.read_bytes().decode()
    lines = existing.splitlines(keepends=True)
    begin_lines = [i for i, line in enumerate(lines) if line.rstrip("\r\n") == MANAGED_BEGIN]
    end_lines = [i for i, line in enumerate(lines) if line.rstrip("\r\n") == MANAGED_END]
    if (
        existing.count(MANAGED_BEGIN) != len(begin_lines)
        or existing.count(MANAGED_END) != len(end_lines)
        or len(begin_lines) != len(end_lines)
        or len(begin_lines) > 1
        or (begin_lines and begin_lines[0] >= end_lines[0])
    ):
        raise SystemExit(f"conflict: {target.name} has an incomplete or ambiguous managed boundary")
    if begin_lines:
        start = sum(len(line) for line in lines[: begin_lines[0]])
        end = sum(len(line) for line in lines[: end_lines[0] + 1])
        target.write_bytes((existing[:start] + block + existing[end:]).encode())
        return
    separator = "" if not existing or existing.endswith(("\n", "\r")) else "\n"
    target.write_bytes((existing + separator + ("\n" if existing else "") + block).encode())


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    dest = Path(sys.argv[1])
    target = dest / ".gitignore"
    write_managed(target, managed_block(dest))
    counted = (
        len([p for p in (dest / ".gitignore.d").iterdir() if p.is_file() and not p.name.startswith(".")])
        if (dest / ".gitignore.d").is_dir()
        else 0
    )
    print(f".gitignore updated from {counted} fragment(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
