#!/usr/bin/env bun
/** Generate ci/plugins-full.toml from local marketplace entries.
 * The profile is intentionally derived from .omp-plugin/marketplace.json so a
 * newly added checkout plugin cannot silently escape the CI estate.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const repo = resolve(dirname(import.meta.path), "..");
const marketplacePath = join(repo, ".omp-plugin/marketplace.json");
const profilePath = join(repo, "ci/plugins-full.toml");
const marketplace = JSON.parse(await readFile(marketplacePath, "utf8")) as { plugins?: Array<{ name?: unknown; source?: unknown }> };
const names = (marketplace.plugins ?? [])
  .filter((entry) => typeof entry.source === "string" && entry.source.startsWith("./"))
  .map((entry) => {
    if (typeof entry.name !== "string" || entry.source !== `./${entry.name}`) throw new Error(`invalid local marketplace entry: ${JSON.stringify(entry)}`);
    return entry.name;
  });
if (new Set(names).size !== names.length) throw new Error("duplicate local marketplace plugin name");
const lines = [
  "# Generated by scripts/write-full-profile.ts; do not edit by hand.",
  "# Run `bun scripts/write-full-profile.ts` after changing marketplace.json.",
  "",
  "[[marketplaces]]",
  'name = "srobroek-omp"',
  'source = "."',
  `plugins = [${names.map((name) => JSON.stringify(name)).join(", ")}]`,
  "",
].join("\n");
if (process.argv.includes("--check")) {
  let current: string;
  try { current = await readFile(profilePath, "utf8"); } catch { throw new Error(`${profilePath} is missing; run without --check`); }
  if (current !== lines) throw new Error(`${profilePath} is stale; run bun scripts/write-full-profile.ts`);
  console.log(`PASS: full profile matches ${names.length} local marketplace plugins`);
} else {
  await writeFile(profilePath, lines);
  console.log(`WROTE: ${profilePath} (${names.length} local marketplace plugins)`);
}
