import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync, copyFileSync } from "node:fs";
import { join, basename } from "node:path";

import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

const STEP_HEADING = /^### (S\d+[a-z]?) — .+ \{#(S\d+[a-z]?)\}\s*$/;
const DELTA_ENTRY = /^- \*\*Δ(\d+)\*\* (\d{4}-\d{2}-\d{2}) · (.+?) · behavior-change\s*$/;
const JOURNEY_ID = /^J\d+$/;
const STEP_REF = /\+?(S\d+[a-z]?)/g;
const RESULTS: Record<string, true> = { pass: true, fail: true, blocked: true, skipped: true };
const STATUSES: Record<string, true> = { draft: true, active: true, deprecated: true };
const REQUIRED_KEYS = ["id", "title", "version", "status", "last_reviewed"] as const;

export type Frontmatter = Record<string, string | string[] | Record<string, string>>;

export function parseFrontmatter(text: string): Frontmatter {
	const lines = text.split("\n");
	if (!lines.length || lines[0].trim() !== "---") return {};
	const fm: Frontmatter = {};
	for (const line of lines.slice(1)) {
		if (line.trim() === "---") return fm;
		if (!line.trim() || line.trimStart().startsWith("#") || !line.includes(":")) continue;
		const idx = line.indexOf(":");
		const key = line.slice(0, idx).trim();
		let raw = line.slice(idx + 1).split(" #")[0].trim();
		if (raw.startsWith("[") && raw.endsWith("]")) {
			const inner = raw.slice(1, -1).trim();
			fm[key] = inner ? inner.split(",").map((v) => v.trim()).filter(Boolean) : [];
		} else if (raw.startsWith("{") && raw.endsWith("}")) {
			const entries: Record<string, string> = {};
			const inner = raw.slice(1, -1).trim();
			for (const part of inner.split(",").map((p) => p.trim()).filter(Boolean)) {
				const c = part.indexOf(":");
				if (c === -1) continue;
				entries[part.slice(0, c).trim()] = part.slice(c + 1).trim();
			}
			fm[key] = entries;
		} else {
			fm[key] = raw;
		}
	}
	return {};
}

export function journeyDirs(root: string): string[] {
	if (!existsSync(root)) return [];
	return readdirSync(root)
		.map((name) => join(root, name))
		.filter((d) => {
			try {
				return statSync(d).isDirectory() && existsSync(join(d, "journey.md"));
			} catch {
				return false;
			}
		})
		.sort();
}

export function latestRun(jdir: string): Frontmatter | null {
	const runsDir = join(jdir, "runs");
	if (!existsSync(runsDir)) return null;
	const runs = readdirSync(runsDir)
		.filter((n) => n.endsWith(".md"))
		.sort()
		.map((n) => join(runsDir, n));
	if (!runs.length) return null;
	const last = runs[runs.length - 1];
	const fm = parseFrontmatter(readFileSync(last, "utf8"));
	fm._file = basename(last);
	return fm;
}

export function openFindings(root: string): Record<string, number> {
	const tracker = join(root, "TRACKER.md");
	const counts: Record<string, number> = {};
	if (!existsSync(tracker)) return counts;
	const text = readFileSync(tracker, "utf8");
	const chunks = text.split("<!-- journey-finding").slice(1);
	for (const chunk of chunks) {
		const jid = chunk.slice(0, 400).match(/journey:\s*(\S+)/);
		const status = chunk.slice(0, 800).match(/status:\s*(\w+)/);
		if (jid && (!status || status[1] === "open")) {
			counts[jid[1]] = (counts[jid[1]] ?? 0) + 1;
		}
	}
	return counts;
}

export function cmdIndex(root: string): { ok: boolean; text: string; count: number } {
	const findings = openFindings(root);
	const rows: string[] = [];
	for (const jdir of journeyDirs(root)) {
		const fm = parseFrontmatter(readFileSync(join(jdir, "journey.md"), "utf8"));
		const run = latestRun(jdir);
		let last = "never";
		if (run) {
			const mode = String(run.mode ?? "full").split("(")[0];
			last = `${run.date ?? "?"} ${run.result ?? "?"} (${mode})`;
		}
		const id = typeof fm.id === "string" ? fm.id : "";
		const nOpen = findings[id] ?? 0;
		const surfaces = Array.isArray(fm.surfaces) ? fm.surfaces.join(", ") : "—";
		const ifc = Array.isArray(fm.interfaces) ? fm.interfaces.join(", ") : "—";
		rows.push(
			`| [${fm.id ?? "?"}](${basename(jdir)}/journey.md) | ${fm.title ?? "?"} | ${fm.status ?? "?"} | v${fm.version ?? "?"} | ${surfaces} | ${ifc} | ${fm.last_reviewed ?? "?"} | ${last} | ${nOpen ? String(nOpen) : "—"} |`,
		);
	}
	const body = [
		"# Journey index",
		"",
		"Generated by `journeys.py index` — do not hand-edit.",
		"",
		"| id | title | status | version | surfaces | interfaces | last_reviewed | last run | open findings |",
		"|---|---|---|---|---|---|---|---|---|",
		...rows,
		"",
	].join("\n");
	writeFileSync(join(root, "INDEX.md"), body, "utf8");
	return { ok: true, text: `INDEX.md: ${rows.length} journeys`, count: rows.length };
}

export function lintJourney(jdir: string, errors: string[], seenIds: Record<string, string>): void {
	const path = join(jdir, "journey.md");
	const text = readFileSync(path, "utf8");
	const rel = `${basename(jdir)}/journey.md`;
	const fm = parseFrontmatter(text);
	if (!Object.keys(fm).length) {
		errors.push(`${rel}: missing or unterminated frontmatter`);
		return;
	}
	for (const key of REQUIRED_KEYS) {
		if (!(key in fm)) errors.push(`${rel}: frontmatter missing \`${key}\``);
	}
	const jid = typeof fm.id === "string" ? fm.id : "";
	if (jid && !JOURNEY_ID.test(jid)) errors.push(`${rel}: id \`${jid}\` does not match J<n>`);
	if (jid in seenIds) errors.push(`${rel}: duplicate id \`${jid}\` (also ${seenIds[jid]})`);
	seenIds[jid] = rel;
	if (jid && !basename(jdir).startsWith(`${jid}-`)) {
		errors.push(`${rel}: directory \`${basename(jdir)}\` does not start with \`${jid}-\``);
	}
	if (typeof fm.status === "string" && !STATUSES[fm.status]) {
		errors.push(`${rel}: status \`${fm.status}\` not in ${JSON.stringify(Object.keys(STATUSES).sort())}`);
	}
	if (fm.version !== undefined && !String(fm.version).match(/^\d+$/)) {
		errors.push(`${rel}: version \`${fm.version}\` is not an integer`);
	}

	const stepIds: string[] = [];
	const lines = text.split("\n");
	lines.forEach((line, i) => {
		const n = i + 1;
		if (line.startsWith("### ") && line.includes("{#")) {
			const m = line.match(STEP_HEADING);
			if (!m) {
				errors.push(`${rel}:${n}: malformed step heading (want \`### S<id> — title {#S<id>}\`)`);
				return;
			}
			if (m[1] !== m[2]) errors.push(`${rel}:${n}: heading id ${m[1]} != anchor ${m[2]}`);
			if (stepIds.includes(m[1])) errors.push(`${rel}:${n}: duplicate step id ${m[1]}`);
			stepIds.push(m[1]);
		} else if (line.startsWith("### S")) {
			errors.push(`${rel}:${n}: step heading missing \`{#S<id>}\` anchor`);
		}
	});

	const version = String(fm.version ?? "").match(/^\d+$/) ? Number(fm.version) : null;
	lines.forEach((line, i) => {
		const n = i + 1;
		const m = line.match(DELTA_ENTRY);
		if (!m) return;
		if (version !== null && Number(m[1]) > version) {
			errors.push(`${rel}:${n}: delta Δ${m[1]} exceeds journey version ${version}`);
		}
		const refs = m[3].match(STEP_REF) ?? [];
		for (const raw of refs) {
			const ref = raw.startsWith("+") ? raw.slice(1) : raw;
			if (!stepIds.includes(ref)) {
				errors.push(`${rel}:${n}: delta Δ${m[1]} references unknown step ${ref}`);
			}
		}
	});

	const runsDir = join(jdir, "runs");
	if (!existsSync(runsDir)) return;
	for (const name of readdirSync(runsDir).filter((n) => n.endsWith(".md")).sort()) {
		const run = join(runsDir, name);
		const rfm = parseFrontmatter(readFileSync(run, "utf8"));
		const rrel = `${basename(jdir)}/runs/${name}`;
		if (!Object.keys(rfm).length) {
			errors.push(`${rrel}: missing frontmatter`);
			continue;
		}
		if (rfm.journey !== jid) errors.push(`${rrel}: journey \`${rfm.journey}\` != \`${jid}\``);
		if (rfm.result !== "pass" && rfm.result !== "fail" && rfm.result !== "blocked") {
			errors.push(`${rrel}: result \`${rfm.result}\` not pass|fail|blocked`);
		}
		const steps = rfm.steps;
		if (steps && typeof steps === "object" && !Array.isArray(steps)) {
			for (const [sid, res] of Object.entries(steps)) {
				if (!RESULTS[res]) {
					errors.push(`${rrel}: step ${sid} result \`${res}\` not in ${JSON.stringify(Object.keys(RESULTS).sort())}`);
				}
				if (!stepIds.includes(sid)) errors.push(`${rrel}: unknown step id ${sid}`);
			}
		}
	}
}

export function cmdLint(root: string): { ok: boolean; text: string; errors: string[] } {
	const errors: string[] = [];
	const seen: Record<string, string> = {};
	const dirs = journeyDirs(root);
	const lines: string[] = [];
	if (!dirs.length) lines.push(`no journeys found under ${root}`);
	for (const jdir of dirs) lintJourney(jdir, errors, seen);
	for (const err of errors) lines.push(`ERROR ${err}`);
	lines.push(`lint: ${dirs.length} journeys, ${errors.length} errors`);
	return { ok: errors.length === 0, text: lines.join("\n"), errors };
}

export function cmdPrune(
	root: string,
	keep: number,
	yes: boolean,
): { ok: boolean; text: string; doomed: string[] } {
	const doomed: string[] = [];
	for (const jdir of journeyDirs(root)) {
		const runsDir = join(jdir, "runs");
		if (!existsSync(runsDir)) continue;
		const runs = readdirSync(runsDir)
			.filter((n) => n.endsWith(".md"))
			.sort()
			.map((n) => join(runsDir, n));
		const extra = keep ? runs.slice(0, Math.max(0, runs.length - keep)) : runs;
		doomed.push(...extra);
	}
	const lines: string[] = [];
	for (const path of doomed) {
		const rel = path.slice(root.length).replace(/^\//, "");
		lines.push(`${yes ? "delete" : "would delete"} ${rel}`);
		if (yes) unlinkSync(path);
	}
	lines.push(`prune: ${doomed.length} run files ${yes ? "deleted" : "to delete (use --yes)"}`);
	return { ok: true, text: lines.join("\n"), doomed };
}

export type JourneysIndexParams = {
	command: "index" | "lint" | "prune";
	journeysDir: string;
	keep?: number;
	yes?: boolean;
};

export function runJourneys(params: JourneysIndexParams): { ok: boolean; text: string } {
	const root = params.journeysDir;
	try {
		if (!existsSync(root) || !statSync(root).isDirectory()) {
			return { ok: false, text: `not a directory: ${root}` };
		}
	} catch {
		return { ok: false, text: `not a directory: ${root}` };
	}
	if (params.command === "index") return cmdIndex(root);
	if (params.command === "lint") return cmdLint(root);
	return cmdPrune(root, params.keep ?? 20, Boolean(params.yes));
}

const FORMULAS_DIR = new URL("../skills/journey-verify/formulas/", import.meta.url).pathname;

export function formulaSources(dir = FORMULAS_DIR): string[] {
	if (!existsSync(dir)) return [];
	return readdirSync(dir)
		.filter((n) => n.endsWith(".formula.toml"))
		.sort()
		.map((n) => join(dir, n));
}

export function installFormulas(
	repoRoot: string,
	force = false,
	sourcesDir = FORMULAS_DIR,
): { ok: boolean; text: string; copied?: number; unchanged?: number } {
	const beadsDir = join(repoRoot, ".beads");
	try {
		if (!existsSync(beadsDir) || !statSync(beadsDir).isDirectory() || statSync(beadsDir).isSymbolicLink()) {
			return { ok: false, text: `ERROR not a Beads workspace: ${repoRoot}` };
		}
	} catch {
		return { ok: false, text: `ERROR not a Beads workspace: ${repoRoot}` };
	}
	const destinationDir = join(beadsDir, "formulas");
	if (existsSync(destinationDir)) {
		const st = statSync(destinationDir);
		if (st.isSymbolicLink() || !st.isDirectory()) {
			return { ok: false, text: `ERROR unsafe formula destination: ${destinationDir}` };
		}
	}
	const sources = formulaSources(sourcesDir);
	if (!sources.length) {
		return { ok: false, text: `ERROR no formula files found in ${sourcesDir}` };
	}
	const unchanged = new Set<string>();
	const unsafe: string[] = [];
	const conflicts: string[] = [];
	for (const source of sources) {
		const destination = join(destinationDir, basename(source));
		if (existsSync(destination)) {
			const st = statSync(destination);
			if (st.isSymbolicLink() || !st.isFile()) {
				unsafe.push(destination);
			} else if (readFileSync(destination).equals(readFileSync(source))) {
				unchanged.add(source);
			} else {
				conflicts.push(destination);
			}
		}
	}
	if (unsafe.length) {
		return { ok: false, text: `ERROR unsafe formula destinations: ${unsafe.join(", ")}` };
	}
	if (conflicts.length && !force) {
		return {
			ok: false,
			text: `ERROR refusing to overwrite divergent formula files: ${conflicts.join(", ")}`,
		};
	}
	mkdirSync(destinationDir, { recursive: true });
	let copied = 0;
	for (const source of sources) {
		if (unchanged.has(source)) continue;
		copyFileSync(source, join(destinationDir, basename(source)));
		copied += 1;
	}
	return {
		ok: true,
		text: `formulas: ${copied} copied, ${unchanged.size} unchanged`,
		copied,
		unchanged: unchanged.size,
	};
}

export default function journeysTool(pi: ExtensionAPI): void {
	const z = pi.zod;
	pi.registerTool({
		name: "journeys_index",
		label: "Journey index/lint/prune",
		description:
			"Index, lint, or prune a user-journeys directory. The repo-copied journeys.py remains the in-repo helper; this tool is the native in-harness equivalent.",
		parameters: z.object({
			command: z.enum(["index", "lint", "prune"]),
			journeysDir: z.string().describe("Path to the journeys directory"),
			keep: z.number().optional().describe("prune: keep newest N runs (default 20)"),
			yes: z.boolean().optional().describe("prune: actually delete (default dry-run)"),
		}),
		approval: (toolCall) => {
			const cmd = (toolCall.input as JourneysIndexParams | undefined)?.command;
			const yes = Boolean((toolCall.input as JourneysIndexParams | undefined)?.yes);
			if (cmd === "lint") return "read";
			if (cmd === "prune" && !yes) return "read";
			return undefined;
		},
		execute: async (_id, params: JourneysIndexParams) => {
			const result = runJourneys(params);
			return {
				content: [{ type: "text", text: result.text }],
				details: { ok: result.ok, command: params.command },
			};
		},
	});

	pi.registerTool({
		name: "journey_install_formulas",
		label: "Install journey formulas",
		description:
			"Copy package-owned journey formula TOMLs into a Beads workspace .beads/formulas/.",
		parameters: z.object({
			repoRoot: z.string().describe("Repository root containing .beads/"),
			force: z.boolean().optional().describe("Overwrite divergent destination files"),
		}),
		execute: async (_id, params: { repoRoot: string; force?: boolean }) => {
			const result = installFormulas(params.repoRoot, Boolean(params.force));
			return {
				content: [{ type: "text", text: result.text }],
				details: {
					ok: result.ok,
					copied: result.copied,
					unchanged: result.unchanged,
				},
			};
		},
	});
}

