#!/usr/bin/env python3
# VENDORED from srobroek/agentic-packages,
# packages/hooks-attribution-guard/scripts/attribution-guard.py.
#
# Copied for its PATTERNS list, which carries several recorded false-positive fixes: the bare
# users.noreply.github.com domain was removed because it is every GitHub user's address, so an
# ordinary human co-author trailer was reported as AI attribution. Rewriting those patterns
# would rediscover each of those cases the hard way.
#
# The upstream `main` reads a PreToolUse JSON payload from stdin and inspects the shell
# COMMAND. A commit-msg hook receives a FILE PATH instead, so attribution_guard.py beside
# this file provides that entry point and imports PATTERNS from here.
#
# NO CHECKER ENFORCES THIS COPY. Re-sync with:
#
#     cp <agentic-packages>/packages/hooks-attribution-guard/scripts/attribution-guard.py \
#        templates/quality/hooks/template/scripts/attribution_patterns.py
"""Warn when a git commit claims an AI agent as an author.

The human is the sole author of record, so a commit must not carry an agent
trailer, an agent signature line, or a "generated by" claim. This is advisory:
it emits allow plus additionalContext and never blocks, because the commit
message is trivially fixable and a denied commit costs more than a nudge.

Scoped to ATTRIBUTION constructs rather than any mention of AI. A commit like
"fix AI model loading bug" or "refactor the claude client wrapper" is ordinary
work and must pass untouched, so every pattern here requires authorship-shaped
context: a trailer key, an explicit generated-by phrase, a known agent signature
URL, or a hyphenated authorship qualifier.
"""

from __future__ import annotations

import json
import re
import sys

# Agents and vendors that ship commit attribution. Matched only inside an
# authorship construct, never on their own -- naming a tool in a commit subject
# is not a claim of authorship.
AGENTS = r"""(?:
    claude | anthropic
  | codex | openai | gpt-?[0-9] | chatgpt
  | copilot
  | cursor
  | devin | cognition
  | aider
  | gemini | bard | google[ -]?ai
  | openhands | all-hands
  | windsurf | codeium
  | continue\.dev
  | sourcegraph | cody
  | tabnine
  | replit[ -]?agent
  | jules
  | goose
  | cline | roo[ -]?code
  | amazon[ -]?q | codewhisperer
  | llm | language[ -]model | ai[ -]agent | an?[ -]ai | ai(?![a-z])
)"""

# Trailer keys that assert co-authorship or agency. `Signed-off-by` counts: it
# is a stronger claim than co-authorship, not a weaker one.
TRAILER_KEYS = (
    r"(?:co-?authored-?by|signed-?off-?by|assisted-?by|generated-?by"
    r"|authored-?by|created-?by|committed-?by|on-?behalf-?of)"
)

PATTERNS: list[tuple[str, str]] = [
    # A trailer key whose value names an agent, on one line.
    (
        rf"(?:^|[\s\"'\\]){TRAILER_KEYS}\s*:[^\n]*{AGENTS}",
        "a commit trailer naming an AI agent",
    ),
    # A trailer key pointing at an agent noreply address, even when the display
    # name is something else.
    #
    # Each entry must identify an AGENT. The bare users.noreply.github.com domain
    # was listed here, but that is every GitHub user's address, so an ordinary human
    # co-author trailer was reported as AI attribution -- the exact false positive
    # this guard is otherwise carefully scoped to avoid. GitHub bot accounts are
    # matched instead by their local part, which ends in `[bot]` or `-bot`.
    # `@openai` likewise needed the dot, or any address at a domain merely
    # containing that substring matched.
    (
        rf"(?:^|[\s\"'\\]){TRAILER_KEYS}\s*:[^\n]*<[^>]*(?:noreply@anthropic|@openai\.|@cursor\.|"
        rf"@cognition|@aider\.|@all-hands|@codeium|"
        rf"(?:\[bot\]|-bot)@users\.noreply\.github\.com)",
        "a commit trailer pointing at an AI agent address",
    ),
    # "Generated with <agent>", "Written by <agent>". A real signature opens a
    # line or the message itself, optionally behind a robot emoji or quoting
    # punctuation. That anchor is what separates a signature from prose about one:
    # this package's own commit messages quote these phrases mid-sentence and must
    # stay clean. The message start counts because a one-line `-m "Generated with
    # X"` puts the phrase immediately after the opening quote, and the escaped \n
    # counts because the payload is one flat command string.
    (
        # The leading run is written with \x20 rather than a literal space:
        # re.VERBOSE strips unescaped whitespace even inside a character class,
        # which silently dropped the space and stopped an emoji-prefixed
        # signature from matching.
        rf"(?:^|\n|\\n|-m\s+|--message[=\s]+)"
        rf"[\x20\t\"'*\#>\-\U0001F916]*"
        rf"(?:generated|written|authored|created|produced|co-created)\s+"
        rf"(?:with|by|using)\s+(?:the\s+|a\s+|an\s+)?{AGENTS}",
        "a generated-with signature line naming an AI agent",
    ),
    # The same phrase where the agent name ENDS the message or line. A signature
    # trails off ("... generated by AI"), whereas prose about attribution keeps
    # going ("... commits generated with Cursor slipped through"), so what follows
    # the agent separates the two even when the phrase is not line-initial.
    (
        rf"(?:generated|written|authored|created|produced|co-created)\s+"
        rf"(?:with|by|using)\s+(?:the\s+|a\s+|an\s+)?{AGENTS}"
        rf"[\x20\t\.\!\"'\)]*(?:$|\n|\\n)",
        "a generated-with attribution closing the message",
    ),
    # Agent signature URLs, which appear even when the trailer is omitted.
    (
        r"claude\.com/claude-code|claude\.ai/code|cursor\.(?:com|sh)/|"
        r"github\.com/features/copilot|devin\.ai|aider\.chat|codeium\.com",
        "an AI agent signature URL",
    ),
    # Hyphenated authorship qualifiers, as a claim about THIS commit. Hyphen
    # only: "AI generated thumbnails" describes a feature, while "AI-generated"
    # claims authorship, and the verbs are authorship ones for the same reason
    # ("AI-powered" is a product description).
    #
    # The qualifier must also open a line or the message, which is what keeps
    # prose that merely quotes the term clean -- including this package's own
    # commit messages and docs, where the phrase is the subject rather than a
    # signature.
    (
        rf"(?:^|\n|\\n|-m\s+|--message[=\s]+)[\x20\t\"'*\#>\-\U0001F916]*"
        rf"(?:ai|llm|agent|bot|machine)-"
        rf"(?:assisted|generated|authored|written|committed)\b",
        "an AI authorship qualifier",
    ),
    # The robot-emoji signature line, which several agents emit. Requires a
    # neighbouring authorship word so a commit that merely uses the emoji passes.
    (
        r"\U0001F916[^\n]{0,40}(?:generated|assisted|authored|written|created)",
        "a robot-emoji agent signature",
    ),
]

COMPILED = [
    (re.compile(pattern, re.IGNORECASE | re.MULTILINE | re.VERBOSE), label)
    for pattern, label in PATTERNS
]

# `git commit` where commit is the subcommand: the first non-option token. Global
# options are allowed between git and commit, so `git -C path commit` fires while
# `git log --grep commit` does not.
GIT_COMMIT = re.compile(
    r"(?:^|[\s/])git(?:\s+-[^\s]+(?:\s+[^-][^\s;&|]*)?)*\s+commit(?:$|\s)"
)

ADVICE = (
    "The human is the sole author of record. Drop the agent trailer, signature "
    "line, generated-with phrase, or AI authorship qualifier from the commit "
    "message and re-commit. Proceeding."
)


def extract_command(payload: str) -> str:
    """Pull the command from a hook payload.

    tool_input is an object for most callers and a bare string for some. The jq
    idiom `.tool_input.command // .tool_input` throws on a string and silently
    skips the guard, so the type is checked instead.
    """
    data = json.loads(payload)
    if not isinstance(data, dict):
        return ""
    tool_input = data.get("tool_input")
    if isinstance(tool_input, str):
        return tool_input
    if isinstance(tool_input, dict):
        command = tool_input.get("command")
        return command if isinstance(command, str) else ""
    return ""


def main() -> int:
    payload = sys.stdin.read()
    # Cheap bail on the raw bytes: this guard only ever acts on a commit. A
    # strict superset of the real trigger, so it cannot mask a command the
    # structured check below would have flagged.
    if "commit" not in payload:
        return 0

    try:
        command = extract_command(payload)
    except (ValueError, TypeError):
        return 0
    if not command or not GIT_COMMIT.search(command):
        return 0

    for pattern, label in COMPILED:
        if pattern.search(command):
            json.dump(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "PreToolUse",
                        "permissionDecision": "allow",
                        "additionalContext": (
                            f"This git commit carries AI authorship attribution "
                            f"({label}). {ADVICE}"
                        ),
                    }
                },
                sys.stdout,
            )
            return 0
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except BaseException:
        # Fail open: an authorship nudge must never wedge a commit.
        raise SystemExit(0)
