#!/usr/bin/env python3
"""Rebuild .github/workflows/ci.yml from the reusable workflows beside it.

    gen_caller.py [<dest>] [--default-branch <name>] [--keep-hand-owned]

A reusable workflow does not run itself: GitHub needs a caller wiring `needs:` and the path
filters between them. Which workflows exist depends on which layers rendered, so the caller
is derived from the directory rather than written by hand, and `just ci-sync` rebuilds it
when a layer is added.

The whole file is rewritten each run, unlike the marker blocks the other generators here
preserve. Every line of a caller is derived from the tree and, when present, the committed
`.ci/members.json` lists the member paths the caller can represent. A ci.yml whose first
line is not the marker is somebody else's file and is refused rather than replaced: take
over only for jobs that the member manifest and reusable workflow tree cannot represent,
such as a container build or a tofu plan, by dropping that line.

The graph it emits:

    changes ─┬─> lint-<lang> ─┐
             └─> test-<lang> ─┤
                              ├──> gate
    quality ──────────────────┤
    security ─────────────────┘

`changes` evaluates every filter once and each language job reads its own key. The filtering
has to sit on the jobs: a workflow gated at `on.push.paths` does not run at all for an
unrelated change, and `gate` is the only required status check, so one that never runs leaves
the pull request unmergeable forever. A filtered job reports `skipped`, which the gate counts
as a pass.

`quality` and `security` wait for nothing. Each reads its own fragment directory and builds
its own matrix, so neither takes a language input nor has a filter to read.

Only `changes` and `gate` receive an input in the single-root case. In a MONOREPO, each
accepted member capability also receives its committed `working-directory`; no path is inferred
from the tree.

Deterministic: languages sort by name and accepted capabilities by member, language, and kind,
so two runs write the same bytes.

Exit codes:
    0  written, nothing here to wire, or hand-owned under --keep-hand-owned
    1  a language whose paths this script does not know
    3  ci.yml is hand-owned, so nothing was written
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

WORKFLOWS = ".github/workflows"
CALLER = f"{WORKFLOWS}/ci.yml"
MEMBERS_FILE = ".ci/members.json"


@dataclass(frozen=True)
class MemberCapability:
    name: str
    path: str
    language: str
    kind: str

    @property
    def job_name(self) -> str:
        return f"{self.kind}-{self.language}-{self.name}"

    @property
    def filter_name(self) -> str:
        return f"{self.language}-{self.name}"


# The first line of the generated file, and this script's claim to it.
MARKER = "# Generated by scripts/gen_caller.py -- edit the wc-* workflows, not this file"

# The host layer's own four. Wired by name rather than discovered: each takes a different
# input, and only one needs a permission the caller has to grant.
HOST = ("wc-changes.yml", "wc-gate.yml", "wc-quality.yml", "wc-security.yml")

# What a language's jobs read, so a change anywhere in its set re-runs them. Grounded in the
# files each lang/* layer renders and the lockfiles its .github/security.d fragment names.
# The layers ship no path fragment, so a language reaching CI is what adds an entry here,
# and one arriving without an entry is refused rather than guessed at.
FILTERS: dict[str, tuple[str, ...]] = {
    "api": ("openapi.yaml", ".vacuum.yaml"),
    "go": ("**/*.go", "**/go.mod", "**/go.sum", ".golangci.yml"),
    "python": ("**/*.py", "**/pyproject.toml", "**/uv.lock", "ruff.toml", "pytest.ini"),
    "rust": (
        "**/*.rs",
        "**/Cargo.toml",
        "**/Cargo.lock",
        "rust-toolchain.toml",
        "clippy.toml",
        "rustfmt.toml",
        "deny.toml",
    ),
    # `tofu` rather than `terraform`: the key is the workflow's own suffix, and the workflow
    # is named for the binary that runs.
    "tofu": ("**/*.tf", "**/*.tfvars", "**/*.tfbackend", ".tflint.hcl"),
    "ts": (
        "**/*.ts",
        "**/*.tsx",
        "**/package.json",
        "**/tsconfig.json",
        "**/bun.lock",
        "**/package-lock.json",
        "**/pnpm-lock.yaml",
        "biome.json",
        ".oxlintrc.json",
    ),
}

def member_error(message: str) -> None:
    raise SystemExit(f"{MEMBERS_FILE}: {message}")


def member_path(value: object) -> str:
    if not isinstance(value, str) or not value:
        member_error("member path must be a non-empty string")
    candidate = PurePosixPath(value)
    if value != "." and (
        "\\" in value
        or not re.fullmatch(r"[A-Za-z0-9._/-]+", value)
        or candidate.is_absolute()
        or candidate.as_posix() != value
        or any(part in ("", ".", "..") for part in candidate.parts)
    ):
        member_error(f"unsafe repository-relative member path {value!r}")
    return value


def member_capabilities(
    repo: Path, languages: dict[str, list[str]]
) -> list[MemberCapability] | None:
    """Read accepted MONOREPO capabilities, or None for a single-root repository."""
    path = repo / MEMBERS_FILE
    if not path.is_file():
        return None
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        member_error(f"cannot read valid JSON ({exc})")
    if not isinstance(document, dict) or not isinstance(document.get("members"), list):
        member_error("expected an object with a members array")

    capabilities: list[MemberCapability] = []
    names: set[str] = set()
    job_ids: set[str] = set()
    for member in document["members"]:
        if not isinstance(member, dict):
            member_error("each member must be an object")
        name = member.get("name")
        if not isinstance(name, str) or not re.fullmatch(
            r"[A-Za-z0-9][A-Za-z0-9_-]*", name
        ):
            member_error(f"member name must be job-safe: {name!r}")
        if name in names:
            member_error(f"duplicate member name {name!r}")
        names.add(name)
        path_value = member_path(member.get("path"))
        declared = member.get("capabilities")
        if not isinstance(declared, dict) or not declared:
            member_error(f"member {name!r} needs a non-empty capabilities object")
        for language, kinds in declared.items():
            if not isinstance(language, str) or not isinstance(kinds, list) or not kinds:
                member_error(f"member {name!r} has invalid capabilities for {language!r}")
            if language not in languages:
                member_error(f"member {name!r} has no reusable workflow for {language!r}")
            for kind in kinds:
                if not isinstance(kind, str) or kind not in languages[language]:
                    member_error(f"member {name!r} has no {kind!r} workflow for {language!r}")
                capability = MemberCapability(name, path_value, language, kind)
                if capability.job_name in job_ids:
                    member_error(f"duplicate generated job id {capability.job_name!r}")
                job_ids.add(capability.job_name)
                capabilities.append(capability)
    return sorted(
        capabilities, key=lambda item: (item.name, item.language, item.kind)
    )


HEADER = f"""\
{MARKER}
#
# The caller. A reusable workflow does not run itself, and which ones exist depends on which
# layers rendered, so `just ci-sync` rebuilds this file from {WORKFLOWS}/.
#
# Path filtering sits on the jobs, never on `on.push.paths`. A workflow gated at the `on:`
# level does not run at all for an unrelated change, and `gate` is the only required status
# check, so one that never runs leaves the pull request unmergeable. A job the filter skipped
# reports `skipped`, which the gate counts as a pass."""

SETTINGS = """\
# The floor every called workflow inherits. Only `security` needs more than this.
permissions:
  contents: read

# A second push to the same ref supersedes the first. Two refs never cancel each other.
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true"""

QUALITY = f"""\
  # No language input: it reads .github/quality.d/ and builds its own matrix. Nothing to
  # filter on either, since its own jobs skip when no fragment supplies one.
  quality:
    uses: ./{WORKFLOWS}/wc-quality.yml"""

SECURITY = f"""\
  security:
    # The scans upload SARIF, and a called workflow cannot hold more than its caller granted.
    # Naming permissions replaces the default set rather than adding to it, so `contents:
    # read` is repeated here.
    permissions:
      contents: read
      security-events: write
    uses: ./{WORKFLOWS}/wc-security.yml"""

# The branch the push trigger names, read back out of the file being replaced. Every other
# asset bakes its own default branch in when it is copied; this file is generated after the
# rest, so the first run passes `--default-branch` and a later bare `just ci-sync` recovers
# it. Without the read-back a re-sync would quietly retrigger a `trunk` repository on `main`.
PUSH_BRANCH = re.compile(r"^    branches: \[([^\]]+)\]$", re.M)


def jobs_by_language(workflows: Path) -> dict[str, list[str]]:
    """{language: kinds} for every wc-<kind>-<language>.yml, in emission order.

    lint and test are counted separately rather than as a pair: lang/api contributes a lint
    workflow and no test one, and requiring a pair would drop it from CI entirely.
    """
    found: dict[str, set[str]] = {}
    for path in workflows.glob("wc-*.yml"):
        _, _, rest = path.stem.partition("-")
        kind, _, language = rest.partition("-")
        if kind in ("lint", "test") and language:
            found.setdefault(language, set()).add(kind)
    return {
        language: [kind for kind in ("lint", "test") if kind in kinds]
        for language, kinds in sorted(found.items())
    }


def filter_paths(language: str, member_path: str | None = None) -> tuple[str, ...]:
    """Every path whose change has to re-run a language or member's jobs."""
    if language not in FILTERS:
        raise SystemExit(
            f"wc-*-{language}.yml contributes jobs for {language!r}, which has no entry in "
            "FILTERS in scripts/gen_caller.py. Add its paths: an unfiltered job runs on every "
            "change, and a guessed filter skips a change it should have tested."
        )
    if member_path is None:
        return (
            *FILTERS[language],
            f"{WORKFLOWS}/wc-*-{language}.yml",
            f".github/actions/setup-{language}/**",
            CALLER,
        )
    scoped = FILTERS[language] if member_path == "." else tuple(
        f"{member_path}/{pattern}" for pattern in FILTERS[language]
    )
    return (
        *scoped,
        f"{WORKFLOWS}/wc-*-{language}.yml",
        f".github/actions/setup-{language}/**",
        CALLER,
        MEMBERS_FILE,
    )


def unwired(workflows: Path, languages: dict[str, list[str]]) -> list[str]:
    """The reusable workflows this script leaves alone, so the file can say so."""
    wired = {f"wc-{kind}-{language}.yml" for language, kinds in languages.items() for kind in kinds}
    return sorted(
        path.name
        for path in workflows.glob("wc-*.yml")
        if path.name not in wired and path.name not in HOST
    )


def header(names: list[str]) -> str:
    """The comment block, naming any reusable workflow the caller deliberately skips.

    Named rather than silently left out: a reader who can see the workflow needs to know
    why nothing calls it, and what to do about it.
    """
    if not names:
        return HEADER
    listed = "\n".join(f"#   {name}" for name in names)
    return (
        f"{HEADER}\n"
        "#\n"
        "# Not wired here:\n"
        f"{listed}\n"
        "#\n"
        "# Each needs a caller decision this script cannot derive from the tree -- a role ARN,\n"
        "# a registry push only on the default branch, a permission grant. A repository using\n"
        "# one owns its caller: drop the marker line above, after which this script refuses the\n"
        "# file rather than rewriting it."
    )


def job_names(
    languages: dict[str, list[str]], capabilities: list[MemberCapability] | None = None
) -> list[str]:
    """Every job the caller emits before the gate, which is what the gate needs."""
    names = ["changes"] if ((languages and capabilities is None) or capabilities) else []
    if capabilities is None:
        names += [f"{kind}-{language}" for language, kinds in languages.items() for kind in kinds]
    else:
        names += [capability.job_name for capability in capabilities]
    return [*names, "quality", "security"]


def changes_job(
    languages: dict[str, list[str]], capabilities: list[MemberCapability] | None = None
) -> str:
    lines = [
        "  # One filter evaluation for the whole run, output as the JSON array of keys that",
        "  # matched. Each set names the language's sources, the manifests and lockfiles that",
        "  # decide what is built, the workflow that runs it, and this file: the pull request",
        "  # wiring a language has to exercise the jobs it adds.",
        "  changes:",
        f"    uses: ./{WORKFLOWS}/wc-changes.yml",
        "    with:",
        "      filters: |",
    ]
    if capabilities is None:
        for language in languages:
            lines.append(f"        {language}:")
            lines += [f"          - '{path}'" for path in filter_paths(language)]
    else:
        seen: set[str] = set()
        for capability in capabilities:
            if capability.filter_name in seen:
                continue
            seen.add(capability.filter_name)
            lines.append(f"        {capability.filter_name}:")
            lines += [
                f"          - '{path}'"
                for path in filter_paths(capability.language, capability.path)
            ]
    return "\n".join(lines)


def language_job(
    kind: str, language: str, capability: MemberCapability | None = None
) -> str:
    name = f"{kind}-{language}" if capability is None else capability.job_name
    filter_name = language if capability is None else capability.filter_name
    lines = [
        f"  {name}:",
        "    needs: changes",
        f"    if: contains(fromJSON(needs.changes.outputs.changes), '{filter_name}')",
        f"    uses: ./{WORKFLOWS}/wc-{kind}-{language}.yml",
    ]
    if capability is not None:
        lines += ["    with:", f"      working-directory: {capability.path}"]
    return "\n".join(lines)



def gate_job(needed: list[str]) -> str:
    return "\n".join(
        [
            "  # The only required status check. It judges every other job's result, so a job",
            "  # added above is covered without touching branch protection.",
            "  gate:",
            "    needs:",
            *(f"      - {name}" for name in needed),
            "    # Without always() the gate is skipped whenever anything it needs was skipped",
            "    # or failed, and a required check that never reports blocks the pull request.",
            "    if: always()",
            f"    uses: ./{WORKFLOWS}/wc-gate.yml",
            "    with:",
            "      needs: ${{ toJSON(needs) }}",
        ]
    )


def push_branch(existing: str, override: str | None) -> str:
    if override:
        return override
    found = PUSH_BRANCH.search(existing)
    return found.group(1) if found else "main"


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="gen_caller.py",
        description="Rebuild .github/workflows/ci.yml from the reusable workflows beside it.",
    )
    parser.add_argument("dest", nargs="?", default=Path("."), type=Path, help="repository root")
    parser.add_argument(
        "--default-branch",
        help="branch the push trigger names; the value already in ci.yml otherwise, then main",
    )
    parser.add_argument(
        "--keep-hand-owned",
        action="store_true",
        help="exit 0 rather than 3 on a hand-owned ci.yml, for a render that must not fail",
    )
    args = parser.parse_args()

    workflows = args.dest / WORKFLOWS
    if not (workflows / "wc-gate.yml").is_file():
        # Nothing to call. A caller naming a workflow that is not there fails at the run
        # rather than at lint time, so writing one would be worse than writing nothing.
        print(f"no {WORKFLOWS}/wc-gate.yml here, so there is no caller to write")
        return 0

    path = args.dest / CALLER
    existing = path.read_text() if path.is_file() else ""
    if existing and not existing.startswith(MARKER):
        report = f"{CALLER} has no generator marker, so it is hand-owned"
        if args.keep_hand_owned:
            print(f"{report}; left alone")
            return 0
        print(
            f"{report}; refusing to overwrite it. Delete the file to hand the caller back "
            "to this script.",
            file=sys.stderr,
        )
        return 3

    languages = jobs_by_language(workflows)
    capabilities = member_capabilities(args.dest, languages)
    branch = push_branch(existing, args.default_branch)
    body = caller(languages, branch, unwired(workflows, languages), capabilities)
    if body != existing:
        path.write_text(body)

    print(f"{CALLER}: {', '.join([*job_names(languages, capabilities), 'gate'])}")
    return 0


def caller(
    languages: dict[str, list[str]],
    branch: str,
    note: list[str],
    capabilities: list[MemberCapability] | None = None,
) -> str:
    """The whole file."""
    top = "\n\n".join(
        [
            header(note),
            "name: CI",
            f"on:\n  push:\n    branches: [{branch}]\n  pull_request:",
            SETTINGS,
            "jobs:",
        ]
    )
    jobs = [changes_job(languages, capabilities)] if (
        (languages and capabilities is None) or capabilities
    ) else []
    if capabilities is None:
        for language, kinds in languages.items():
            jobs += [language_job(kind, language) for kind in kinds]
    else:
        jobs += [
            language_job(capability.kind, capability.language, capability)
            for capability in capabilities
        ]
    jobs += [QUALITY, SECURITY, gate_job(job_names(languages, capabilities))]
    return f"{top}\n" + "\n\n".join(jobs) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
